### ISSUE TITLE
How to use this js file in Angular 9?

### ISSUE THREAD

**Issue by Topiya** [erpardeepjain/dynamic-sitemap-update-js#2]
Can you please let me know how to use this code in Angular 9 to create dynamic sitemap.xml in src folder of project ?

**Comment by erpardeepjain** [comment]
Hey @Topiya , Just create a normal JS script file and add this file on the root level of your Angular Project. Now run manually or by some automation this script.
Please make sure the path to your `sitemap.xml` should be correct. otherwise, it won't work. 
Let me know in case of any query.

**Comment by Topiya** [comment]
Thanks for the reply. I tried as you suggested but getting below error.

`Uncaught ReferenceError: require is not defined`

**Comment by Topiya** [comment]
Thanks for the reply. I tried as you suggested but getting below error. Can you provide any solution for this?

`Uncaught ReferenceError: require is not defined`

**Comment by erpardeepjain** [comment]
@Topiya I have create one repo for you, please refer to this - https://github.com/erpardeepjain/angular-dynamic-sitemap-update-script

I hope this will clear out your all doubts.

Points to remember - 

* Script entry in package.json file.
* Path to sitemap.xml file.
* Your API endpoints should be in working state.

**Comment by Topiya** [comment]
Thanks for this repository. Here we can generate sitemap.xml using `npm run sitemap` without any error,  but I am searching for a solution where I can call sitemap-update.js function saveNewSitemap() from .ts of angular instead of using command. When I am trying to do this here, it gives  `Uncaught ReferenceError: require is not defined`  error. Is there any solution for this?

**Comment by erpardeepjain** [comment]
@Topiya `require()` is a NodeJS/commonjs/systemjs (server) function, Angular controller (.ts file) will be executed in the browser, so this will not be available on the client-side, that is the reason I have chosen command-line script over the internal calling function from some service/component.

if you get any alternate let me know in the comment box, as of now I am going to close this issue.
